language: en

site:
  name:
    class: text
    custom: Efu
  siteIcon: /img/pwa/favicon.ico
  icon: /img/avatar.png

nav:
  group:
    projects:
      Solitude: https://github.com/valor-x/hexo-theme-solitude || /img/pwa/favicon.ico

  menu:
    Library:
      Archives: /archives/ || st-folder-fill
      Categories: /categories/ || st-checkbox-multiple-blank-fill
      Tags: /tags/ || st-price-tag-fill
    Links:
      Moments: /moments/ || st-wifi-fill
      Friends: /links/ || st-group-fill
      Traveling: javascript:travelling() || st-gift-fill
    Oneself:
      Equipment: /equipment/ || st-laptop-line
      Toolbox: /tlink/ || st-tools-fill
      Music: /music/ || st-disc-fill
    Contact:
      About Us: /about/ || st-contacts-fill

  right:
    random: true
    console: true
    custom:
    # - name: å¼€å¾€ - å‹é“¾æ¥åŠ› # æ˜¾ç¤ºæ–‡å­— / Displayed text
    #   url: https://www.travellings.cn/go.html # è·³è½¬é“¾æ¥ / Jump link
    #   icon: st-train-line # å›¾æ ‡ / Icon
    #   onclick: # ç‚¹å‡»äº‹ä»¶ / Click event
    #   id: travellings_button # id


hometop:
  enable: true
  banner:
    title: Be careful<br > and enjoy it.
    url: EFU.ME
    icon:
      HTML:
        img: https://7.isyangs.cn/34/65f2e42921677-34.png
        color: "#e9572b"
      JS:
        img: https://7.isyangs.cn/34/65f2e43ceddda-34.png
        color: "#f7cb4f"
      Git:
        img: https://7.isyangs.cn/34/65f2e499066fa-34.png
        color: "#df5b40"

  group:
  # çƒ­é—¨: /tags/çƒ­é—¨/ || st-fire-fill || linear-gradient(to right,#f65,#ffbf37)
  # æ•™ç¨‹: /tags/æ•™ç¨‹/ || st-book-mark-fill || linear-gradient(to right,#358bff,#15c6ff)
  # ç²¾é€‰: /tags/ç²¾é€‰/ || st-star-smile-fill || linear-gradient(to right,#18e7ae,#1eebeb)

  recommendList:
    sup: Sup
    title: Solitude Docs
    url: https://solitude-docs.efu.me/
    img: /img/default.png
    color: "#4fa5ce"

aside:
  home:
    noSticky: "about"
    Sticky: "allInfo"
  post:
    noSticky: "about"
    Sticky: "newestPost"
  page:
    noSticky: "about"
    Sticky: "newestPost,allInfo"
  card:
    author:
      img: https://7.isyangs.cn/34/6602e49f7acab-34.png
      sticker: https://7.isyangs.cn/34/65f2e4e0423cc-34.png
    url: /about/
    content: Share your love for programming, your yearning for a better life, and your exploration of the ocean of knowledge.
    content2:
    sayhello:
      morning: ğŸ˜„ Have a nice day.
      noon: ğŸ’¤ Have a nice nap.
      afternoon: ğŸµ Have an afternoon tea.
      night: ğŸ® playtime.
      goodnight: ğŸ˜´ Hava a good night.
    sayhello2:
      - ğŸ¤–ï¸ Digital technology
      - ğŸ” Share & Help
      - ğŸ  Smart home
      - ğŸ”¨ Design and development
      - ğŸƒ Down-to-earth
      - ğŸ§± Team group
      - ğŸ® Esports games
    information:
      Github: https://github.com/efuo || st-github-line
      Bilibili: https://space.bilibili.com/1329819902 || st-bilibili-line

  flip:
    favicon:
    face:
    backface:
    backcolor: "var(--efu-blue)"

  toc:
    post: true
    page: false
    vague: true

  tags:
    enable: false
    limit: 20
    highlight: false
    list:
    # - "Solitude"

  archive:
    enable: false
    type: "month"

  siteinfo:
    postcount: true
    wordcount: false
    pv: true
    uv: true
    updatetime: true
    runtimeenable: true
    runtime: "2023-04-20 00:00:00"

index_post_list:
  direction: column
  content: 3
  length: 500
  cover: both

page:
  error: true
  tags: true
  categories: true
  default:
    cover:

post:
  default:
    cover:
    locate: HengYang
    copyright:
      enable: true
      license: CC BY-NC-SA 4.0
      licenurl: https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh
  meta:
    date: false # å‘å¸ƒæ—¥æœŸ / Release date
    updated: false # æ›´æ–°æ—¥æœŸ / Update date
    locate: false # ä½ç½® / Location
    wordcount: false # å­—æ•° / Number of words
    readtime: false # è®¿é—® / uv
    pv: false # æµè§ˆé‡ / pv
    comment: false # è¯„è®ºæ•° / Comment count
  award:
    enable: false
    wechat: https://7.isyangs.cn/34/65f2e5814db1a-34.png
    alipay: https://7.isyangs.cn/34/65f2e5a6d2ef5-34.png
    url: /about
  rss: # /atom.xml
  covercolor:
    enable: true
    mode: local # localï¼šæœ¬åœ°å–è‰² / apiï¼šimg2colorå–è‰² : local: local color / api: img2color color
    api: https://api.qjqq.cn/api/Imgcolor?img= # apiåœ°å€ / api address
    time: 43200000 # apiå–è‰²é—´éš”ï¼ˆæ¯«ç§’ï¼‰ï¼Œé»˜è®¤ä¸º12å°æ—¶ / api color interval (milliseconds), default is 12 hours

theme_color:
  dark: "#ffc848" # æš—è‰²æ¨¡å¼ / Dark mode
  dark_op: "#f2b94b23" # æš—è‰²æ¨¡å¼é€æ˜ / Dark mode transparent
  dark_op_deep: "#f2b94bdd" # æš—è‰²æ¨¡å¼é€æ˜æ·±è‰² / Dark mode transparent dark
  dark_none: "#f2b94b00" # æš—è‰²æ¨¡å¼é€æ˜æ— è‰² / Dark mode transparent colorless
  light: "#425AEF" # äº®è‰²æ¨¡å¼ / Light mode
  light_op: "#4259ef23" # äº®è‰²æ¨¡å¼é€æ˜ / Light mode transparent
  light_op_deep: "#4259efdd" # äº®è‰²æ¨¡å¼é€æ˜æ·±è‰² / Light mode transparent dark
  light_none: "#4259ef01" # äº®è‰²æ¨¡å¼é€æ˜æ— è‰² / Light mode transparent colorless

display_mode:
  type: auto # auto: è‡ªåŠ¨åˆ‡æ¢ / dark: æš—è‰²æ¨¡å¼ / light: äº®è‰²æ¨¡å¼ / auto: automatic switching / dark: dark mode / light: light mode
  universe: true # å¼€å¯åæš—è‰²æ¨¡å¼ä¸‹ä¼šæ˜¾ç¤ºæ˜Ÿç©ºèƒŒæ™¯ / After opening, the dark mode will display the starry sky background


related_post:
  enable: false
  # æ¨èæ–‡ç« æ•°é‡
  # Number of recommended articles
  limit: 2
  # æ ¹æ®åˆ›å»ºæ—¥æœŸï¼ˆcreatedï¼‰æˆ–æ˜¯æ›´æ–°æ—¥æœŸï¼ˆupdatedï¼‰
  # According to the creation date (created) or the update date (updated)
  date_type: created

footer:
  # åº•éƒ¨ä¸Šæ–¹ä¸€æ’å›¾æ ‡
  # Bottom row of icons
  information:
    left: # å·¦ä¾§æ˜¾ç¤ºå›¾æ ‡
      Github: https://github.com/efuo || st-github-line # åç§°ï¼šé“¾æ¥ || å›¾æ ‡ / Name: link || icon
      Mail: mailto:o@efu.me || st-mail-line
    right: # å³ä¾§æ˜¾ç¤ºå›¾æ ‡
      Bilibili: https://space.bilibili.com/1329819902 || st-bilibili-line
      æŠ–éŸ³: https://v.douyin.com/iJsLc8jt/ || st-douyin-fill

  group:
    Nav:
      Archives: /archives/
      Categories: /categories/
      Tags: /tags/
  # æœåŠ¡:
  #   é˜¿é‡Œäº‘: https://aliyun.com/
  #   51laç»Ÿè®¡: https://v6.51.la/
  #   ç™¾åº¦ç»Ÿè®¡: https://tongji.baidu.com/
  # æ”¯æŒ:
  #   æ‰“èµè®°å½•: /about/
  # åè®®:
  #   Cookies: /cookies/
  #   ç”¨æˆ·åè®®: /privacy/
  #   ç‰ˆæƒåè®®: /copyright/

  # é¡µè„šéšæœºå‹é“¾
  # Random links at footer
  # warning: æ‰“å¼€å‰å¿…é¡»å…ˆé…ç½®links
  # warning: links must be configured before opening
  randomlink: false
  # éšç§åŠ©æ‰‹å³ä¾§å¼¹çª—ï¼Œå¡«å†™è·¯å¾„åå¼€å¯
  # Privacy assistant right pop-up window, fill in the path to open
  privacy: # /privacy/
  # ç‰ˆæƒ(Copyright)
  license: # /license/
  # é¡µè„šå³ä¾§é“¾æ¥ï¼Œä¾‹å¦‚ï¼šICPå¤‡æ¡ˆå·ã€å…¬å®‰å¤‡æ¡ˆå·ç­‰
  # Footer right link, such as: ICP filing number, public security filing number, etc.
  links:
    # ä¸ºäº†ä¸»é¢˜èƒ½å¤Ÿå¾—åˆ°æ›´å¤šçš„æ”¯æŒï¼Œå»ºè®®ä¿ç•™ä¸»é¢˜é“¾æ¥
    # In order for the theme to get more support, it is recommended to keep the theme link
    - name: Theme
      url: https://github.com/valor-x/hexo-theme-solitude
    # - name: è®¢é˜…
    #   url: /atom.xml

# 404 é¡µé¢(404 page)
errorpage:
  # å›¾ç‰‡
  # image
  img: https://7.isyangs.cn/34/65f2e65eae32a-34.png
  # æ–‡å­—
  # text
  text: =awa= é¡µé¢èµ°ä¸¢äº†
  # æ¨èæ–‡ç« åˆ—è¡¨
  # Recommended article list
  recommendList: true

# å³åˆ»çŸ­æ–‡
# talk now
# å‰ç½®è¦æ±‚ï¼šéœ€é…ç½®å³åˆ»çŸ­æ–‡é¡µé¢
# Pre-requirements: talk now page needs to be configured
says:
  enable: false
  # ä¸»é¡µçš„å³åˆ»è½®æ’­æ¡
  # Talk carousel bar on the homepage
  home_mini: false
  # 1ï¼šå¼ æ´ªheoæ ·å¼ / 2ï¼šLeonusæ ·å¼
  # 1: Zhang Hong heo style / 2: Leonus style
  style: 1
  # å³åˆ»çŸ­æ–‡ä»…å±•ç¤ºå‰næ¡
  # Talk short text only shows the first n
  strip: 30

# -------------------------
# meeting-apiï¼Œç”¨äºç•Œé¢ä¸­çš„éŸ³ä¹èƒ¶å›Šå’ŒéŸ³ä¹é¦†é¡µï¼Œå¯è‡ªå®šä¹‰apiï¼Œä¸ä¼šè¯·å‹¿åŠ¨ã€‚
# meeting-api, used for music capsules and music halls in the interface, can customize api, do not move if you don't know.
meting_api: "https://meting.qjqq.cn/?server=:server&type=:type&id=:id&auth=:auth&r=:r" #è‡ªå®šä¹‰api
# éŸ³ä¹é¦†é¡µ
# music page
music:
  enable: false
  # éŸ³ä¹IDï¼šæ­Œå•ID / ä¸“è¾‘ID / æ­Œæ‰‹ID
  # Music ID: playlist ID / album ID / singer ID
  id: 1994908354
  # æ’­æ”¾åˆ—è¡¨çš„æœåŠ¡å•†ã€‚neteaseï¼šç½‘æ˜“äº‘ / tencentï¼šè…¾è®¯ / kugouï¼šé…·ç‹— / xiamiï¼šå°ç±³ / baiduï¼šç™¾åº¦
  # Music service provider. netease: Netease Cloud / tencent: Tencent / kugou: Kugou / xiaomi: Xiaomi / baidu: Baidu
  server: netease
  # æ’­æ”¾åˆ—è¡¨çš„ç±»å‹ã€‚songï¼šå•æ›² / playlistï¼šæ­Œå• / albumï¼šä¸“è¾‘ / artistï¼šæ­Œæ‰‹
  # Type of playlist. song: Single / playlist: Playlist / album: Album / artist: Singer
  type: playlist
  # åˆå§‹éŸ³é‡ã€‚0.8 = 80%ï¼ŒèŒƒå›´ 0 åˆ° 1
  # Initial volume. 0.8 = 80%, range 0 to 1
  volume: 0.8
  # æ˜¯å¦å¼€å¯äº’æ–¥æ¨¡å¼ï¼Œå³åŒæ—¶åªèƒ½æœ‰ä¸€ä¸ªæ’­æ”¾å™¨æ’­æ”¾
  # Whether to enable mutex mode, that is, only one player can play at the same time
  mutex: true

# éŸ³ä¹èƒ¶å›Š
# capsule music
capsule:
  enable: true
  # æ­Œå•id / playlist id
  id: 8407304077
  # æ’­æ”¾åˆ—è¡¨çš„æœåŠ¡å•†ã€‚neteaseï¼šç½‘æ˜“äº‘ / tencentï¼šè…¾è®¯ / kugouï¼šé…·ç‹— / xiamiï¼šå°ç±³ / baiduï¼šç™¾åº¦
  # Music service provider. netease: Netease Cloud / tencent: Tencent / kugou: Kugou / xiaomi: Xiaomi / baidu: Baidu
  server: netease
  # æ’­æ”¾åˆ—è¡¨çš„ç±»å‹ã€‚songï¼šå•æ›² / playlistï¼šæ­Œå• / albumï¼šä¸“è¾‘ / artistï¼šæ­Œæ‰‹
  # Type of playlist. song: Single / playlist: Playlist / album: Album / artist: Singer
  type: playlist

# å‹é“¾é±¼å¡˜
# Links fish pond
moments:
  # enable
  enable: false
  # API åœ°å€
  # example: https://example.com/
  api: # https://example.com/
  # åŠ è½½å¤±è´¥æ˜¾ç¤ºå›¾ç‰‡ / Loading failed display image
  error_img: /img/logo.png
  # æ’åºè§„åˆ™ï¼šcreatedï¼šæŒ‰åˆ›å»ºæ—¶é—´æ’åº / updatedï¼šæŒ‰æ›´æ–°æ—¶é—´æ’åº
  # Sort rule: created: Sort by creation time / updated: Sort by update time
  sort_rule: created
  # ç¼“å­˜è¿‡æœŸæ—¶é—´ï¼ˆå¤©ï¼‰ï¼Œé»˜è®¤ä¸º1å¤© / Cache expiration time (days), default is 1 day
  expire_days: 1
  # é¡µé¢åˆå§‹åŒ–åŠ è½½æ•°é‡ï¼Œé»˜è®¤ä¸º10æ¡ / Page initialization loading quantity, default is 10
  page_init_number: 10
  # é¡µé¢ç¿»é¡µåŠ è½½æ•°é‡ï¼Œé»˜è®¤ä¸º5æ¡ / Page turning loading quantity, default is 5
  page_turning_number: 5
  # é±¼å¡˜éšæœºæ–‡ç«  / Fish pond random article
  angle: false
  appjs: https://cdn.cbd.int/st-source@1.0.3/js/fcircle.min.js
  bundlejs: https://cdn.cbd.int/st-source/js/moment/bundle.min.js
  randompostjs: https://cdn.cbd.int/st-source/js/moment/random_post.min.js

# å¿«æ·èœå•ä½ 
# quick menu
keyboard:
  enable: true # æ˜¯å¦å¼€å¯é”®ç›˜æ§åˆ¶ / Whether to enable keyboard control
  # é”®ç›˜æ§åˆ¶é…ç½®
  # Keyboard control configuration
  list:
    # name: æŒ‰é”®åç§°(name)
    # key: æŒ‰é”®(Key)
    # func: æ–¹æ³•(function)
    # sco: scoå†…ç½®æ–¹æ³•(sco.'function')
    # url: è·³è½¬é“¾æ¥(link)
    # ------------------
    - name: Turn off key
      key: K
      func: keyboard
    - name: Open Console
      key: A
      sco: showConsole
    - name: Play/pause music
      key: M
      sco: musicToggle
    - name: Open Friends
      key: L
      url: "/links/"

# æ‡’åŠ è½½
# lazyload
lazyload:
  enable: true
  field: site # post, site
  # åŠ è½½ä¸­æ˜¾ç¤ºå›¾ç‰‡
  # Loading display image
  placeholder: /img/loading.gif
  # åŠ è½½å¤±è´¥æ˜¾ç¤ºå›¾ç‰‡
  # Loading failed display image
  errorimg: /img/error_load.png

# åŠ è½½åŠ¨ç”»
# loading animation
loading:
  # å…¨å±€åŠ è½½åŠ¨ç”»
  # Global loading animation
  fullpage: true
  # é¡¶éƒ¨åŠ è½½èƒ¶å›Š
  # Top loading capsule
  pace: true

highlight:
  enable: true
  limit: 200 # ä»£ç è¡Œé«˜é™åˆ¶ / Code line limit
  copy: true # æ˜¯å¦å¼€å¯å¤åˆ¶æŒ‰é’® / Whether to enable the copy button
  expand: true # æ˜¯å¦é»˜è®¤å±•å¼€ / Whether to expand by default
  # ä»£ç å—æ ·å¼
  # Code block style
  theme: mac # default: é»˜è®¤ / mac : apple terminal
  # ä»£ç é…è‰²
  # Code color
  color: darcula # default: é»˜è®¤  / dark / funky / okaidia / tomorrow / twilight / darcula / solarized-dark / solarized-light / material / github

# å›¾ç‰‡ç¯ç®±
# image lightbox
# warningï¼šå¼€å¯å‰ä¸‹æ–¹çš„fancyboxæˆ–mediumZoomå¿…é¡»æ‰“å¼€ä¸€ä¸ª
# warning: One of the fancybox or mediumZoom below must be turned on before turning on
lightbox: true
# fancybox
# https://fancyapps.com/fancybox/
fancybox: true
# mediumZoom
mediumZoom: false

# mermaid
# https://mermaid.js.org/
mermaid: false

# ç®€ç¹è½¬æ¢
# Simplified and Traditional Chinese conversion
translate:
  enable: false
  # the language of website (1 - Traditional Chinese/ 2 - Simplified Chineseï¼‰
  defaultEncoding: 2
  # Time delay
  translateDelay: 0

# Open Graph
# https://ogp.me/
# https://developers.facebook.com/docs/sharing/webmasters/
opengraph:
  enable: true
  options:
  #  twitter_card:
  #  twitter_image:
  #  twitter_id:
  #  twitter_site:
  #  google_plus:
  #  fb_admins:
  #  fb_app_id:

# å­—æ•°ç»Ÿè®¡
# word count
# warningï¼šå¼€å¯å‰éœ€è¦å®‰è£…å­—æ•°ç»Ÿè®¡æ’ä»¶
# warning: You need to install the word count plugin before turning it on
wordcount: false

# è®¿é—®ç»Ÿè®¡
# access statistics
busuanzi: true

# æœç´¢
# search
# warningï¼šå¼€å¯å‰éœ€è¦å®‰è£…æœç´¢æ’ä»¶
# warning: You need to install the search plugin before turning it on
search:
  enable: false
  # algolia, local
  type: local
  # æ¨èæ ‡ç­¾
  # Recommended tags
  tags:
  #  - Solitude
  #  - Hexo
  algolia:
  # hits:
  #   per_page: 6
  local:
    preload: false
    CDN:

# rightside(å³é”®èœå•)
# right menu
rightside:
  enable: false

# æ–‡ç« æ‘˜è¦AI
# post abstract AI
post_ai:
  enable: false
  # å³ä¾§æ˜¾ç¤ºçš„æ¨¡å‹åç§°
  # Model name displayed on the right
  modelName: GPT 4
  # key
  # å…·ä½“è·å–æ–¹æ³•è§æ–‡æ¡£
  # Specific acquisition method, see the document
  key:
  # è‡ªä»‹
  # talk
  talk: æˆ‘æ˜¯ Efu å¼€å‘çš„æ‘˜è¦ç”ŸæˆåŠ©ç†EfuGPTï¼ŒEfuGPTåœ¨é™æ€éƒ¨ç½²æ—¶è¿›è¡Œæ‘˜è¦çš„æ’°å†™ï¼Œå¹¶ä¸”åœ¨è®¿å®¢è®¿é—®æ—¶é€šè¿‡EfuCorrectionè½¬è¯‘åçš„æ–‡æœ¬æ‘˜è¦å®ç°å·¥å…·ã€‚æˆ‘åœ¨è¿™é‡Œåªè´Ÿè´£å·²ç»ç”Ÿæˆçš„æ‘˜è¦æ˜¾ç¤ºï¼Œä½ æ— æ³•ä¸æˆ‘ç›´æ¥æ²Ÿé€šï¼Œä½†æˆ‘å¯ä»¥å›ç­”ä¸€äº›é¢„è®¾çš„é—®é¢˜ã€‚
  # éšæœºæ–‡ç« æŒ‰é’®
  # Random post button
  randomPost: false
  # ä¸¾æŠ¥é“¾æ¥ï¼Œä¸å¡«ä¸æ˜¾ç¤º
  # Report link, do not fill in and do not display
  report: https://efu.me/
  # åº•éƒ¨æç¤º
  # Bottom tip
  tips: æ­¤å†…å®¹æ ¹æ®æ–‡ç« ç”Ÿæˆï¼Œå¹¶ç»è¿‡äººå·¥å®¡æ ¸ï¼Œä»…ç”¨äºæ–‡ç« å†…å®¹çš„è§£é‡Šä¸æ€»ç»“

# latex å…¬å¼æ”¯æŒ
# latex formula support
# docs: https://solitude-docs.efu.me/configuration/extra#æ•°å­¦å…¬å¼
katex:
  enable: false
  per_page: false # æ˜¯å¦åœ¨æ¯é¡µéƒ½åŠ è½½ / Whether to load on each page
  copytex: false # æ˜¯å¦å¼€å¯å¤åˆ¶å…¬å¼ / Whether to enable copy formula

# è¯„è®º
# comment
comment:
  enable: false
  type: # waline, twikoo
  commentBarrage: false # çƒ­è¯„å¼€å…³ / Hot comment switch
  newComment: false # æœ€æ–°è¯„è®ºå¼€å…³ / Latest comment switch
  # åŒ¿åè¯„è®ºå‰éƒ¨åˆ†éšæœºä¿¡æ¯ / Anonymous comment front random information
  randomInfoStart:
    - "èªæ•çš„"
    - "å¯çˆ±çš„"
    - "ç¾ä¸½çš„"
  # åŒ¿åè¯„è®ºåéƒ¨åˆ†éšæœºä¿¡æ¯ / Anonymous comment after random information
  randomInfoEnd:
    - "ç™½èœ"
    - "å°å¯çˆ±"
    - "å°ä»™å¥³"
  # twikoo é…ç½®ä¿¡æ¯
  # twikoo settings
  twikoo: # https://twikoo.js.org/
    envId: # url: https://twikoo.sondy.top/
    lang: "zh-CN" # è¯­è¨€
    accessToken: # accessToken
  # waline é…ç½®ä¿¡æ¯
  # waline settings
  waline: # https://waline.js.org/
    envId: # url: https://waline.wzsco.top
    pageview: true # æ˜¯å¦å¼€å¯é¡µé¢è®¿é—®é‡ç»Ÿè®¡ / Whether to enable page access statistics
    option: # walineé…ç½®é¡¹ / waline configuration item

# ç«™ç‚¹éªŒè¯
# Site verification
# ä»…éœ€è¦å¡«å†™éªŒè¯ä»£ç å³å¯ï¼Œè­¬å¦‚ï¼šcodeva-KReTIJu5us
# Only need to fill in the verification code, such as: codeva-KReTIJu5us
verify_site:
# - name: google-site-verification
#   content: xxxxxx
# - name: baidu-site-verification
#   content: xxxxxxx

# CSS å‰ç¼€
# CSS prefix
# æœ‰äº› CSS å¹¶ä¸æ˜¯æ‰€æœ‰æµè§ˆå™¨éƒ½æ”¯æŒï¼Œéœ€è¦å¢åŠ å¯¹åº”çš„å‰ç¼€æ‰ä¼šç”Ÿæ•ˆ
# Some CSS is not supported by all browsers, and you need to add the corresponding prefix to take effect
# å¼€å¯ css_prefix åï¼Œä¼šè‡ªåŠ¨ä¸ºä¸€äº› CSS å¢åŠ å‰ç¼€ã€‚ï¼ˆä¼šå¢åŠ  20%çš„ä½“ç§¯ï¼‰
# After opening css_prefix, some CSS will be automatically prefixed. (Will increase 20% of the volume)
css_prefix: true

# Font å­—ä½“
# Font
font:
  font-size: 16px
  code-font-size: 16px
  font-family: '"PingFang SC","Hiragino Sans GB","Microsoft YaHei"'
  code-font-family: '"monospace", "monospace"'

# æ’å…¥ä»£ç åˆ°å¤´éƒ¨ </head> ä¹‹å‰ å’Œ åº•éƒ¨ </body> ä¹‹å‰
# Insert code before </head> and before </body>
# æ’å…¥é¢å¤–ä»£ç  å¦‚ï¼šç»Ÿè®¡ï¼Œå¹¿å‘Šç­‰
# Insert additional code such as: statistics, advertising, etc.
extends:
  head: # åœ¨headä¸­æ’å…¥ / Insert in head
  # - <script src="https://cdn.bootcdn.net/ajax/libs/pace/1.2.4/pace.min.js"></script>
  body: # åœ¨bodyä¸­æ’å…¥ / Insert in body

# PWA
# https://developer.mozilla.org/zh-CN/docs/Web/Progressive_web_apps
# docs: https://solitude-docs.efu.me/configuration/extra#pwa
pwa:
  enable: false
  manifest: /manifest.json # manifest.json æ–‡ä»¶è·¯å¾„
  theme_color: "#006a73" # ä¸»é¢˜é¢œè‰²
  mask_icon: /img/logo.png # é®ç½©å›¾æ ‡
  apple_touch_icon: /img/logo.png # è‹¹æœè§¦æ‘¸å›¾æ ‡
  bookmark_icon: /img/logo.png # ä¹¦ç­¾å›¾æ ‡
  favicon_32_32: /img/logo.png # 32x32å›¾æ ‡
  favicon_16_16: /img/logo.png # 16x16å›¾æ ‡

# è°·æ­Œå¹¿å‘Š (Google Adsense)
google_adsense:
  enable: false
  auto_ads: false # è‡ªåŠ¨å¹¿å‘Šå…³é—­ååˆ™ä¸ºæ‰‹åŠ¨å¹¿å‘Š / After auto ads are turned off, it is manual ads
  enable_page_level_ads: true # é¡µé¢çº§å¹¿å‘Š / Page-level ads
  js: https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js # è°·æ­Œå¹¿å‘Šjs / Google Adsense js
  # client id
  # æ— è®ºæ˜¯å¦å¼€å¯è‡ªåŠ¨å¹¿å‘Šï¼Œéƒ½éœ€è¦å¡«å†™ client id
  # Whether to enable auto ads or not, you need to fill in the client id
  client: # ca-pub-XXXXXXXXXXXXXX
  # slot id
  # åªæœ‰å…³é—­è‡ªåŠ¨å¹¿å‘Šæ—¶æ‰éœ€è¦å¡«å†™ slot idï¼Œå¯ä»¥åœ¨è°·æ­Œå¹¿å‘Šåå° æŒ‰å¹¿å‘Šå•å…ƒä¸­åˆ›å»ºå¹¿å‘Šä½åè·å–
  # Only when auto ads are turned off, you need to fill in the slot id, which can be obtained after creating an ad space in the Google Adsense background according to the ad unit
  slot: # 4236388782

# CDN
# Don't modify the following settings unless you know how they work
# éå¿…è¦è¯·ä¸è¦ä¿®æ”¹
CDN:
  # The CDN provider of internal scripts (ä¸»é¢˜å†… js çš„ cdn é…ç½®)
  # option: local/jsdelivr/unpkg/cdnjs/custom
  # Dev version can only choose. ( devç‰ˆæœ¬åªèƒ½ä¸º local )
  internal: local
  # The CDN provider of third party scripts (ç¬¬ä¸‰æ–¹ js çš„ cdn é…ç½®)
  # option: jsdelivr/unpkg/cdnjs/custom
  third_party: cdnjs

  # Add version number to url, true or false
  version: true

  # Custom format
  # For example: https://cdn.staticfile.net/${cdnjs_name}/${version}/${min_cdnjs_file}
  custom_format: https://cdn.staticfile.net/${cdnjs_name}/${version}/${min_cdnjs_file}

  option:
    solitude_css: https://cdn2.codesign.qq.com/icons/7pOrz0WXB5ZWJPX/latest/iconfont.css
    # algolia_search:
    # instantsearch:
    # pjax:
    # twikoo:
    # waline_js:
    # waline_css:
    # sharejs:
    # sharejs_css:
    # katex:
    # katex_copytex:
    # lazyload:
    # aplayer_css:
    # aplayer_js:
    # meting_js:
    # pace_js:
    # lunr_js:
    # swiper_css:
    # swiper_js:
    # busuanzi_js:
    # snackbar_js:
