language: en

site:
  name:
    class: text
    custom: Efu
  siteIcon: /img/pwa/favicon.ico
  icon: /img/avatar.png

nav:
  group:
    projects:
      Solitude: https://github.com/valor-x/hexo-theme-solitude || /img/pwa/favicon.ico

  menu:
    Library:
      Archives: /archives/ || st-folder-fill
      Categories: /categories/ || st-checkbox-multiple-blank-fill
      Tags: /tags/ || st-price-tag-fill
    Links: /links/
    #    Oneself:
    #      Equipment: /equipment/ || st-laptop-line
    #      Toolbox: /tlink/ || st-tools-fill
    About: /about/

  right:
    random: true
    console: true
    custom:
    # - name: å¼€å¾€ - å‹é“¾æ¥åŠ› # æ˜¾ç¤ºæ–‡å­— / Displayed text
    #   url: https://www.travellings.cn/go.html # è·³è½¬é“¾æ¥ / Jump link
    #   icon: st-train-line # å›¾æ ‡ / Icon
    #   onclick: # ç‚¹å‡»äº‹ä»¶ / Click event
    #   id: travellings_button # id


hometop:
  enable: true
  banner:
    title: Be careful<br > and enjoy it.
    url: EFU.ME
    icon:
      Kotlin:
        img: /img/icon/kotlin.png
        color: "var(--efu-blue)"
      Csharp:
        img: /img/icon/csharp.png
        color: "var(--efu-purple)"
      Nuxt:
        img: /img/icon/nuxt.png
        color: '#0E182A'
      NPM:
        img: /img/icon/npm.png
        color: var(--efu-white)
      Sketch:
        img: /img/icon/sketch.png
        color: var(--efu-white)
      Final Cut Pro:
        img: /img/icon/final_cut_pro.png
        color: var(--efu-white)
      PS:
        img: /img/icon/ps.png
        color: '#001E36'
      AI:
        img: /img/icon/ai.png
        color: '#330202'

  group:
  # çƒ­é—¨: /tags/çƒ­é—¨/ || st-fire-fill || linear-gradient(to right,#f65,#ffbf37)
  # æ•™ç¨‹: /tags/æ•™ç¨‹/ || st-book-mark-fill || linear-gradient(to right,#358bff,#15c6ff)
  # ç²¾é€‰: /tags/ç²¾é€‰/ || st-star-smile-fill || linear-gradient(to right,#18e7ae,#1eebeb)

  recommendList:
    sup: Sup
    title: Solitude Docs
    url: https://solitude-docs.efu.me/
    img: /img/default.png
    color: "#4fa5ce"

aside:
  home:
    noSticky: "about"
    Sticky: "allInfo"
  post:
    noSticky: "about"
    Sticky: "newestPost"
  page:
    noSticky: "about"
    Sticky: "newestPost,allInfo"
  card:
    author:
      img: https://7.isyangs.cn/34/6602e49f7acab-34.png
      sticker: https://7.isyangs.cn/34/65f2e4e0423cc-34.png
    url: /about/
    content: Share your love for programming, your yearning for a better life, and your exploration of the ocean of knowledge.
    content2:
    sayhello:
      morning: ğŸ˜„ Have a nice day.
      noon: ğŸ’¤ Have a nice nap.
      afternoon: ğŸµ Have an afternoon tea.
      night: ğŸ® playtime.
      goodnight: ğŸ˜´ Hava a good night.
    sayhello2:
      - ğŸ¤–ï¸ Digital technology
      - ğŸ” Share & Help
      - ğŸ  Smart home
      - ğŸ”¨ Design and development
      - ğŸƒ Down-to-earth
      - ğŸ§± Team group
      - ğŸ® Esports games
    information:
      Github: https://github.com/efuo || st-github-line
      Bilibili: https://space.bilibili.com/1329819902 || st-bilibili-line

  flip:
    favicon:
    face:
    backface:
    backcolor: "var(--efu-blue)"

  toc:
    post: true
    page: false
    vague: true

  tags:
    enable: false
    limit: 20
    highlight: false
    list:
    # - "Solitude"

  archive:
    enable: false
    type: "month"

  siteinfo:
    postcount: true
    wordcount: false
    pv: false
    uv: false
    updatetime: false
    runtimeenable: true
    runtime: "2023-04-20 00:00:00"

index_post_list:
  direction: row
  content: 2
  length: 500
  cover: both

page:
  error: true
  tags: true
  categories: true
  default:
    cover:

post:
  default:
    cover:
    locate: HengYang
    copyright:
      enable: true
      license: CC BY-NC-SA 4.0
      licenurl: https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh
  meta:
    date: true
    updated: true
    locate: true
    wordcount: true
    readtime: true
    pv: true
    comment: true
  award:
    enable: true
    appreciators: /about
    title: Thank you for the appreciation.
    desc: Because of your support, I realized the value of writing articles.
    list:
      - name: Alipay
        qcode: https://7.isyangs.cn/34/65f2e5a6d2ef5-34.png
        color: var(--efu-blue)
  rss: # /atom.xml
  covercolor:
    enable: true
    mode: local
    api: https://api.qjqq.cn/api/Imgcolor?img=
    time: 43200000

theme_color:
  dark: "#ffc848"
  dark_op: "#f2b94b23"
  dark_op_deep: "#f2b94bdd"
  dark_none: "#f2b94b00"
  light: "#425AEF"
  light_op: "#4259ef23"
  light_op_deep: "#4259efdd"
  light_none: "#4259ef01"

display_mode:
  type: auto
  universe: true


related_post:
  enable: false
  limit: 2
  date_type: created

footer:
  information:
    left: # å·¦ä¾§æ˜¾ç¤ºå›¾æ ‡
      Github: https://github.com/efuo || st-github-line # åç§°ï¼šé“¾æ¥ || å›¾æ ‡ / Name: link || icon
      Mail: mailto:o@efu.me || st-mail-line
    right: # å³ä¾§æ˜¾ç¤ºå›¾æ ‡
      Bilibili: https://space.bilibili.com/1329819902 || st-bilibili-line
      æŠ–éŸ³: https://v.douyin.com/iJsLc8jt/ || st-douyin-fill

  group:
    Nav:
      Archives: /archives/
      Categories: /categories/
      Tags: /tags/
  # æœåŠ¡:
  #   é˜¿é‡Œäº‘: https://aliyun.com/
  #   51laç»Ÿè®¡: https://v6.51.la/
  #   ç™¾åº¦ç»Ÿè®¡: https://tongji.baidu.com/
  # æ”¯æŒ:
  #   æ‰“èµè®°å½•: /about/
  # åè®®:
  #   Cookies: /cookies/
  #   ç”¨æˆ·åè®®: /privacy/
  #   ç‰ˆæƒåè®®: /copyright/

  randomlink: true
  privacy: / # /privacy/
  license: / # /license/
  links:
    - name: Theme
      url: https://github.com/valor-x/hexo-theme-solitude
    - name: RSS
      url: /atom.xml

errorpage:
  img: https://7.isyangs.cn/34/65f2e65eae32a-34.png
  text: =awa= Not Found
  recommendList: true

says:
  enable: false
  home_mini: false
  style: 1
  strip: 30

meting_api: "https://meting.qjqq.cn/?server=:server&type=:type&id=:id&auth=:auth&r=:r" #è‡ªå®šä¹‰api
music:
  enable: false
  id: 9486968429
  server: netease
  type: playlist
  volume: 0.8
  mutex: true

capsule:
  enable: true
  id: 9486968429
  server: netease
  type: playlist

keyboard:
  enable: true
  list:
    - name: Turn off key
      key: K
      sco: switchKeyboard
    - name: Open Console
      key: A
      sco: showConsole
    - name: Play/pause music
      key: M
      sco: musicToggle
    - name: Open Friends
      key: L
      url: "/links/"

lazyload:
  enable: true
  field: site
  placeholder: /img/loading.gif
  errorimg: /img/error_load.png

loading:
  fullpage: true
  pace: true

highlight:
  enable: true
  limit: 200
  copy: true
  expand: true
  theme: mac
  color: solarized-dark # default: é»˜è®¤  / dark / funky / okaidia / tomorrow / twilight / darcula / solarized-dark / solarized-light / material / github

lightbox: true
fancybox: true
mediumZoom: false

mermaid: false

opengraph:
  enable: true
  options:
  #  twitter_card:
  #  twitter_image:
  #  twitter_id:
  #  twitter_site:
  #  google_plus:
  #  fb_admins:
  #  fb_app_id:

wordcount: true

busuanzi: false

search:
  enable: false
  # algolia, local
  type: local
  # æ¨èæ ‡ç­¾
  # Recommended tags
  tags:
  #  - Solitude
  #  - Hexo
  algolia:
  # hits:
  #   per_page: 6
  local:
    preload: false
    CDN:

rightside:
  enable: false

katex:
  enable: false
  per_page: false # æ˜¯å¦åœ¨æ¯é¡µéƒ½åŠ è½½ / Whether to load on each page
  copytex: false # æ˜¯å¦å¼€å¯å¤åˆ¶å…¬å¼ / Whether to enable copy formula

# è¯„è®º
# comment
comment:
  enable: false
  type: # waline, twikoo
  commentBarrage: false # çƒ­è¯„å¼€å…³ / Hot comment switch
  newComment: false # æœ€æ–°è¯„è®ºå¼€å…³ / Latest comment switch
  randomInfoStart:
    - "èªæ•çš„"
    - "å¯çˆ±çš„"
    - "ç¾ä¸½çš„"
  randomInfoEnd:
    - "ç™½èœ"
    - "å°å¯çˆ±"
    - "å°ä»™å¥³"
  twikoo: # https://twikoo.js.org/
    envId: # url: https://twikoo.sondy.top/
    lang: "zh-CN" # è¯­è¨€
    accessToken: # accessToken

verify_site:

css_prefix: false

font:
  font-size: 16px
  code-font-size: 16px
  font-family: '"PingFang SC","Hiragino Sans GB","Microsoft YaHei"'
  code-font-family: '"monospace", "monospace"'

extends:
  head: # åœ¨headä¸­æ’å…¥ / Insert in head
  body: # åœ¨bodyä¸­æ’å…¥ / Insert in body

pwa:
  enable: false
  manifest: /manifest.json # manifest.json æ–‡ä»¶è·¯å¾„
  theme_color: "#006a73" # ä¸»é¢˜é¢œè‰²
  mask_icon: /img/logo.png # é®ç½©å›¾æ ‡
  apple_touch_icon: /img/logo.png # è‹¹æœè§¦æ‘¸å›¾æ ‡
  bookmark_icon: /img/logo.png # ä¹¦ç­¾å›¾æ ‡
  favicon_32_32: /img/logo.png # 32x32å›¾æ ‡
  favicon_16_16: /img/logo.png # 16x16å›¾æ ‡

google_adsense:
  enable: false
  auto_ads: false # è‡ªåŠ¨å¹¿å‘Šå…³é—­ååˆ™ä¸ºæ‰‹åŠ¨å¹¿å‘Š / After auto ads are turned off, it is manual ads
  enable_page_level_ads: true # é¡µé¢çº§å¹¿å‘Š / Page-level ads
  js: https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js # è°·æ­Œå¹¿å‘Šjs / Google Adsense js
  client: # ca-pub-XXXXXXXXXXXXXX
  slot: # 4236388782

CDN:
  internal: cdnjs
  third_party: cdnjs

  version: true

  custom_format: https://cdn.staticfile.net/${cdnjs_name}/${version}/${min_cdnjs_file}

  option:
    solitude_css: https://cdn2.codesign.qq.com/icons/7pOrz0WXB5ZWJPX/latest/iconfont.css